[package]
authors = ["Tarun Verghis <tarun.verghis@gmail.com>"]
edition = "2018"
name = "aoc07"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = {version = "6.0.1", features = ["alloc"]}
